### ISSUE TITLE
Android 12 phone restart with any of the mirror apps and all versions of CarStream

### ISSUE THREAD

**Issue by mcrownover** [shmykelsa/AAAD#189]
After installing any of the mirror apps or any version of CarStream and then launching any of those app it works for a while.  But if I try to load any "real" AA app like Maps or Message my phone will restart.  I am connected wireless to the head unit.  Below is the debug info generated by the phone.  I think the issue is with however AAAD injects the information into Android Auto since it happens on all apps.

java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = nzw)
at android.os.Parcel.readSerializable(Parcel.java:3513)
at android.os.Parcel.readValue(Parcel.java:3277)
at android.os.Parcel.readArrayMapInternal(Parcel.java:3623)
at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
at android.os.BaseBundle.unparcel(BaseBundle.java:236)
at android.os.BaseBundle.keySet(BaseBundle.java:569)
at android.content.Intent.toUriInner(Intent.java:11054)
at android.content.Intent.toUriFragment(Intent.java:11002)
at android.content.Intent.toUri(Intent.java:10993)
at com.android.server.am.BroadcastQueue.logBroadcastBegin(BroadcastQueue.java:2388)
at com.android.server.am.BroadcastQueue.processNextBroadcastLocked(BroadcastQueue.java:1046)
at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:1003)
at com.android.server.am.BroadcastQueue.access$000(BroadcastQueue.java:85)
at com.android.server.am.BroadcastQueue$BroadcastHandler.handleMessage(BroadcastQueue.java:203)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loopOnce(Looper.java:238)
at android.os.Looper.loop(Looper.java:357)
at android.os.HandlerThread.run(HandlerThread.java:67)
at com.android.server.ServiceThread.run(ServiceThread.java:44)
Caused by: java.lang.ClassNotFoundException: nzw
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:454)
at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:682)
at android.os.Parcel$2.resolveClass(Parcel.java:3504)
at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1703)
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1594)
at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1824)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1409)
at java.io.Obj

**Comment by shmykelsa** [comment]
AAAD is just an app installer and won't directly interfere with Android Auto. You are probably looking for a solution elsewhere.
